/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HardControl */

#ifndef _Included_HardControl
#define _Included_HardControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HardControl
 * Method:    adcOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_HardControl_adcOpen
  (JNIEnv *, jclass);

/*
 * Class:     HardControl
 * Method:    adcRead
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HardControl_adcRead
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
